/**
 * Generates one .ts file per Phosphor icon in components/icons/,
 * plus a barrel index.ts. Run with: deno task update-icons
 */

// Resolve assets dir from the package entry point (dist/index.mjs → assets/regular)
const entryUrl = import.meta.resolve("@phosphor-icons/core");
const packageDir = new URL("../", entryUrl).pathname;
const ASSETS_DIR = `${packageDir}assets/regular`;
const FILL_ASSETS_DIR = `${packageDir}assets/fill`;
const OUTPUT_DIR = "./components/icons";

// Fill-weight variants to emit alongside the regular set (e.g. `StarFill` for a
// selected rating star). Allowlisted — the full fill set would double the dir.
const FILL_ICONS = ["star"];

// Reserved JS identifiers that need remapping
const NAME_MAP: Record<string, string> = {
  Infinity: "InfinitySymbol",
};

function toPascalCase(name: string): string {
  const pascal = name.split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
  return NAME_MAP[pascal] ?? pascal;
}

function toKebabCase(pascal: string): string {
  return pascal.replace(/(?<!^)(?=[A-Z])/g, "-").toLowerCase();
}

function extractSvgContent(svg: string): string {
  return svg.replace(/<svg[^>]*>/, "").replace(/<\/svg>/, "").trim();
}

const icons: Array<[string, string]> = [];

for await (const entry of Deno.readDir(ASSETS_DIR)) {
  if (!entry.isFile || !entry.name.endsWith(".svg")) continue;

  const content = await Deno.readTextFile(`${ASSETS_DIR}/${entry.name}`);
  const pascalName = toPascalCase(entry.name.replace(".svg", ""));
  icons.push([pascalName, extractSvgContent(content)]);
}

for (const name of FILL_ICONS) {
  const content = await Deno.readTextFile(
    `${FILL_ASSETS_DIR}/${name}-fill.svg`,
  );
  icons.push([toPascalCase(`${name}-fill`), extractSvgContent(content)]);
}

icons.sort(([a], [b]) => a.localeCompare(b));

await Deno.mkdir(OUTPUT_DIR, { recursive: true });

for (const [name, svg] of icons) {
  const kebab = toKebabCase(name);
  await Deno.writeTextFile(
    `${OUTPUT_DIR}/${kebab}.ts`,
    `export const ${name} = \`${svg}\`;\n`,
  );
}

const barrel = "// generated by deno task update-icons\n" +
  icons.map(([name]) => `export * from "./${toKebabCase(name)}.ts";`).join(
    "\n",
  ) + "\n";

await Deno.writeTextFile(`${OUTPUT_DIR}/index.ts`, barrel);

console.log(`Wrote ${icons.length} icon files → ${OUTPUT_DIR}/`);
